# Generated by Django 4.2.2 on 2023-06-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="sold_for",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
